package com.lin.po;

public class Chats extends BasePo{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_chats.ID
     *
     * @mbg.generated Sat Mar 19 07:10:00 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_chats.CUSTOMER_GROUP_ID
     *
     * @mbg.generated Sat Mar 19 07:10:00 CST 2022
     */
    private Long customerGroupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_chats.SENDER
     *
     * @mbg.generated Sat Mar 19 07:10:00 CST 2022
     */
    private Long sender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_chats.RECIPIENT
     *
     * @mbg.generated Sat Mar 19 07:10:00 CST 2022
     */
    private Long recipient;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_chats.CONTENT
     *
     * @mbg.generated Sat Mar 19 07:10:00 CST 2022
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_chats.FILE_URL
     *
     * @mbg.generated Sat Mar 19 07:10:00 CST 2022
     */
    private String fileUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_chats.READ_FLAG
     *
     * @mbg.generated Sat Mar 19 07:10:00 CST 2022
     */
    private String readFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_chats.RECIPIENT_FLAG
     *
     * @mbg.generated Sat Mar 19 07:10:00 CST 2022
     */
    private String recipientFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_chats.CREATE_ID
     *
     * @mbg.generated Sat Mar 19 07:10:00 CST 2022
     */
    private Long createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_chats.CREATE_TIME
     *
     * @mbg.generated Sat Mar 19 07:10:00 CST 2022
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_chats.UPDATE_ID
     *
     * @mbg.generated Sat Mar 19 07:10:00 CST 2022
     */
    private Long updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_chats.UPDATE_TIME
     *
     * @mbg.generated Sat Mar 19 07:10:00 CST 2022
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_chats.ID
     *
     * @return the value of cs_chats.ID
     *
     * @mbg.generated Sat Mar 19 07:10:00 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_chats.ID
     *
     * @param id the value for cs_chats.ID
     *
     * @mbg.generated Sat Mar 19 07:10:00 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_chats.CUSTOMER_GROUP_ID
     *
     * @return the value of cs_chats.CUSTOMER_GROUP_ID
     *
     * @mbg.generated Sat Mar 19 07:10:00 CST 2022
     */
    public Long getCustomerGroupId() {
        return customerGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_chats.CUSTOMER_GROUP_ID
     *
     * @param customerGroupId the value for cs_chats.CUSTOMER_GROUP_ID
     *
     * @mbg.generated Sat Mar 19 07:10:00 CST 2022
     */
    public void setCustomerGroupId(Long customerGroupId) {
        this.customerGroupId = customerGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_chats.SENDER
     *
     * @return the value of cs_chats.SENDER
     *
     * @mbg.generated Sat Mar 19 07:10:00 CST 2022
     */
    public Long getSender() {
        return sender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_chats.SENDER
     *
     * @param sender the value for cs_chats.SENDER
     *
     * @mbg.generated Sat Mar 19 07:10:00 CST 2022
     */
    public void setSender(Long sender) {
        this.sender = sender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_chats.RECIPIENT
     *
     * @return the value of cs_chats.RECIPIENT
     *
     * @mbg.generated Sat Mar 19 07:10:00 CST 2022
     */
    public Long getRecipient() {
        return recipient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_chats.RECIPIENT
     *
     * @param recipient the value for cs_chats.RECIPIENT
     *
     * @mbg.generated Sat Mar 19 07:10:00 CST 2022
     */
    public void setRecipient(Long recipient) {
        this.recipient = recipient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_chats.CONTENT
     *
     * @return the value of cs_chats.CONTENT
     *
     * @mbg.generated Sat Mar 19 07:10:00 CST 2022
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_chats.CONTENT
     *
     * @param content the value for cs_chats.CONTENT
     *
     * @mbg.generated Sat Mar 19 07:10:00 CST 2022
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_chats.FILE_URL
     *
     * @return the value of cs_chats.FILE_URL
     *
     * @mbg.generated Sat Mar 19 07:10:00 CST 2022
     */
    public String getFileUrl() {
        return fileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_chats.FILE_URL
     *
     * @param fileUrl the value for cs_chats.FILE_URL
     *
     * @mbg.generated Sat Mar 19 07:10:00 CST 2022
     */
    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_chats.READ_FLAG
     *
     * @return the value of cs_chats.READ_FLAG
     *
     * @mbg.generated Sat Mar 19 07:10:00 CST 2022
     */
    public String getReadFlag() {
        return readFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_chats.READ_FLAG
     *
     * @param readFlag the value for cs_chats.READ_FLAG
     *
     * @mbg.generated Sat Mar 19 07:10:00 CST 2022
     */
    public void setReadFlag(String readFlag) {
        this.readFlag = readFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_chats.RECIPIENT_FLAG
     *
     * @return the value of cs_chats.RECIPIENT_FLAG
     *
     * @mbg.generated Sat Mar 19 07:10:00 CST 2022
     */
    public String getRecipientFlag() {
        return recipientFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_chats.RECIPIENT_FLAG
     *
     * @param recipientFlag the value for cs_chats.RECIPIENT_FLAG
     *
     * @mbg.generated Sat Mar 19 07:10:00 CST 2022
     */
    public void setRecipientFlag(String recipientFlag) {
        this.recipientFlag = recipientFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_chats.CREATE_ID
     *
     * @return the value of cs_chats.CREATE_ID
     *
     * @mbg.generated Sat Mar 19 07:10:00 CST 2022
     */
    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_chats.CREATE_ID
     *
     * @param createId the value for cs_chats.CREATE_ID
     *
     * @mbg.generated Sat Mar 19 07:10:00 CST 2022
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_chats.CREATE_TIME
     *
     * @return the value of cs_chats.CREATE_TIME
     *
     * @mbg.generated Sat Mar 19 07:10:00 CST 2022
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_chats.CREATE_TIME
     *
     * @param createTime the value for cs_chats.CREATE_TIME
     *
     * @mbg.generated Sat Mar 19 07:10:00 CST 2022
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_chats.UPDATE_ID
     *
     * @return the value of cs_chats.UPDATE_ID
     *
     * @mbg.generated Sat Mar 19 07:10:00 CST 2022
     */
    public Long getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_chats.UPDATE_ID
     *
     * @param updateId the value for cs_chats.UPDATE_ID
     *
     * @mbg.generated Sat Mar 19 07:10:00 CST 2022
     */
    public void setUpdateId(Long updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_chats.UPDATE_TIME
     *
     * @return the value of cs_chats.UPDATE_TIME
     *
     * @mbg.generated Sat Mar 19 07:10:00 CST 2022
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_chats.UPDATE_TIME
     *
     * @param updateTime the value for cs_chats.UPDATE_TIME
     *
     * @mbg.generated Sat Mar 19 07:10:00 CST 2022
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_chats
     *
     * @mbg.generated Sat Mar 19 07:10:00 CST 2022
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Chats other = (Chats) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCustomerGroupId() == null ? other.getCustomerGroupId() == null : this.getCustomerGroupId().equals(other.getCustomerGroupId()))
            && (this.getSender() == null ? other.getSender() == null : this.getSender().equals(other.getSender()))
            && (this.getRecipient() == null ? other.getRecipient() == null : this.getRecipient().equals(other.getRecipient()))
            && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()))
            && (this.getFileUrl() == null ? other.getFileUrl() == null : this.getFileUrl().equals(other.getFileUrl()))
            && (this.getReadFlag() == null ? other.getReadFlag() == null : this.getReadFlag().equals(other.getReadFlag()))
            && (this.getRecipientFlag() == null ? other.getRecipientFlag() == null : this.getRecipientFlag().equals(other.getRecipientFlag()))
            && (this.getCreateId() == null ? other.getCreateId() == null : this.getCreateId().equals(other.getCreateId()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateId() == null ? other.getUpdateId() == null : this.getUpdateId().equals(other.getUpdateId()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_chats
     *
     * @mbg.generated Sat Mar 19 07:10:00 CST 2022
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCustomerGroupId() == null) ? 0 : getCustomerGroupId().hashCode());
        result = prime * result + ((getSender() == null) ? 0 : getSender().hashCode());
        result = prime * result + ((getRecipient() == null) ? 0 : getRecipient().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        result = prime * result + ((getFileUrl() == null) ? 0 : getFileUrl().hashCode());
        result = prime * result + ((getReadFlag() == null) ? 0 : getReadFlag().hashCode());
        result = prime * result + ((getRecipientFlag() == null) ? 0 : getRecipientFlag().hashCode());
        result = prime * result + ((getCreateId() == null) ? 0 : getCreateId().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateId() == null) ? 0 : getUpdateId().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }
}