package com.lin.po;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class Chats extends BasePo{
    public static final String READ_FLAG_UNREAD="0";//未读
    public static final String READ_FLAG_READ="1";//已读
    public static final String READ_FLAG_CANCEL="2"; //撤销
    public static final String READ_FLAG_DELETE="3"; //删除

    public static final String RECIPIENT_FLAG_CUSTOMER="0"; //客户关系
    public static final String RECIPIENT_FLAG_GROUP="1";    //群组
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_chats.ID
     *
     * @mbg.generated Sat Mar 19 07:10:00 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_chats.CUSTOMER_GROUP_ID
     *
     * @mbg.generated Sat Mar 19 07:10:00 CST 2022
     */
    private Long customerGroupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_chats.SENDER
     *
     * @mbg.generated Sat Mar 19 07:10:00 CST 2022
     */
    private Long sender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_chats.RECIPIENT
     *
     * @mbg.generated Sat Mar 19 07:10:00 CST 2022
     */
    private Long recipient;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_chats.CONTENT
     *
     * @mbg.generated Sat Mar 19 07:10:00 CST 2022
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_chats.FILE_URL
     *
     * @mbg.generated Sat Mar 19 07:10:00 CST 2022
     */
    private String fileUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_chats.READ_FLAG
     *
     * @mbg.generated Sat Mar 19 07:10:00 CST 2022
     */
    private String readFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_chats.RECIPIENT_FLAG
     *
     * @mbg.generated Sat Mar 19 07:10:00 CST 2022
     */
    private String recipientFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_chats.CREATE_ID
     *
     * @mbg.generated Sat Mar 19 07:10:00 CST 2022
     */
    private Long createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_chats.CREATE_TIME
     *
     * @mbg.generated Sat Mar 19 07:10:00 CST 2022
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_chats.UPDATE_ID
     *
     * @mbg.generated Sat Mar 19 07:10:00 CST 2022
     */
    private Long updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_chats.UPDATE_TIME
     *
     * @mbg.generated Sat Mar 19 07:10:00 CST 2022
     */
    private String updateTime;

}