package com.lin.po;

import lombok.Getter;
import lombok.Setter;

import java.util.List;

@Getter
@Setter
public class Comments extends BasePo{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_comments.ID
     *
     * @mbg.generated Wed Apr 20 20:36:41 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_comments.PARENT_ID
     *
     * @mbg.generated Wed Apr 20 20:36:41 CST 2022
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_comments.LIFE_ID
     *
     * @mbg.generated Wed Apr 20 20:36:41 CST 2022
     */
    private Long lifeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_comments.CUSTOMER_ID
     *
     * @mbg.generated Wed Apr 20 20:36:41 CST 2022
     */
    private Long customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_comments.CONTENTS
     *
     * @mbg.generated Wed Apr 20 20:36:41 CST 2022
     */
    private String contents;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_comments.THUMBSUP_TIMES
     *
     * @mbg.generated Wed Apr 20 20:36:41 CST 2022
     */
    private Integer thumbsupTimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_comments.CREATE_ID
     *
     * @mbg.generated Wed Apr 20 20:36:41 CST 2022
     */
    private Long createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_comments.CREATE_TIME
     *
     * @mbg.generated Wed Apr 20 20:36:41 CST 2022
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_comments.UPDATE_ID
     *
     * @mbg.generated Wed Apr 20 20:36:41 CST 2022
     */
    private Long updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_comments.UPDATE_TIME
     *
     * @mbg.generated Wed Apr 20 20:36:41 CST 2022
     */
    private String updateTime;

    private List<Comments> nodes;
}