package com.lin.po;

import lombok.Getter;
import lombok.Setter;

import java.util.List;

@Getter
@Setter
public class Customer extends BasePo{

    public static final String GENDER_MALE = "male";  //男性
    public static final String GENDER_FEMALE = "female"; //女性
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer.ID
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer.CUSTOMER_NO
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    private String customerNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer.NAMESPACE
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    private String namespace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer.ROOM
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    private String room;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer.PORTRAIT
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    private String portrait;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer.PASSWORD
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer.OPENID
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    private String openid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer.LEVEL_NO
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    private String levelNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer.CUSTOMER_NAME
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    private String customerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer.GENDER
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer.NATION
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    private String nation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer.CARD_TYPE
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    private String cardType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer.CARD_NAME
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    private String cardName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer.CARD_ID
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    private String cardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer.MOBILE
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer.EMAIL
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer.STATUS
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer.CREATE_ID
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    private Long createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer.CREATE_TIME
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer.UPDATE_ID
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    private Long updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer.UPDATE_TIME
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    private String updateTime;

    private Long customerGroupId;

    private List<CustomerRels> customerRels;

    /**
     * 用于做条件进行查询是否需要查询出包含群组
     * 0：不包含
     * 1：包含
     */
    private String incloudGroupFlag;
}