package com.lin.po;

public class CustomerGroup extends BasePo{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer_group.ID
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer_group.CUSTOMER_GROUP_NO
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    private String customerGroupNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer_group.GROUP_FLAG
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    private String groupFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer_group.NAMESPACE
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    private String namespace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer_group.ROOM
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    private String room;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer_group.PORTRAIT
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    private String portrait;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer_group.CUSTOMER_GROUP_NAME
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    private String customerGroupName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer_group.SENDER
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    private String sender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer_group.CONTENT
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer_group.END_TIME
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    private String endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer_group.STATUS
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer_group.CREATE_ID
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    private Long createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer_group.CREATE_TIME
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer_group.UPDATE_ID
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    private Long updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer_group.UPDATE_TIME
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_customer_group.ID
     *
     * @return the value of cs_customer_group.ID
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_customer_group.ID
     *
     * @param id the value for cs_customer_group.ID
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_customer_group.CUSTOMER_GROUP_NO
     *
     * @return the value of cs_customer_group.CUSTOMER_GROUP_NO
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    public String getCustomerGroupNo() {
        return customerGroupNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_customer_group.CUSTOMER_GROUP_NO
     *
     * @param customerGroupNo the value for cs_customer_group.CUSTOMER_GROUP_NO
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    public void setCustomerGroupNo(String customerGroupNo) {
        this.customerGroupNo = customerGroupNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_customer_group.GROUP_FLAG
     *
     * @return the value of cs_customer_group.GROUP_FLAG
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    public String getGroupFlag() {
        return groupFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_customer_group.GROUP_FLAG
     *
     * @param groupFlag the value for cs_customer_group.GROUP_FLAG
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    public void setGroupFlag(String groupFlag) {
        this.groupFlag = groupFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_customer_group.NAMESPACE
     *
     * @return the value of cs_customer_group.NAMESPACE
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    public String getNamespace() {
        return namespace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_customer_group.NAMESPACE
     *
     * @param namespace the value for cs_customer_group.NAMESPACE
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    public void setNamespace(String namespace) {
        this.namespace = namespace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_customer_group.ROOM
     *
     * @return the value of cs_customer_group.ROOM
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    public String getRoom() {
        return room;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_customer_group.ROOM
     *
     * @param room the value for cs_customer_group.ROOM
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    public void setRoom(String room) {
        this.room = room;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_customer_group.PORTRAIT
     *
     * @return the value of cs_customer_group.PORTRAIT
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    public String getPortrait() {
        return portrait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_customer_group.PORTRAIT
     *
     * @param portrait the value for cs_customer_group.PORTRAIT
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    public void setPortrait(String portrait) {
        this.portrait = portrait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_customer_group.CUSTOMER_GROUP_NAME
     *
     * @return the value of cs_customer_group.CUSTOMER_GROUP_NAME
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    public String getCustomerGroupName() {
        return customerGroupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_customer_group.CUSTOMER_GROUP_NAME
     *
     * @param customerGroupName the value for cs_customer_group.CUSTOMER_GROUP_NAME
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    public void setCustomerGroupName(String customerGroupName) {
        this.customerGroupName = customerGroupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_customer_group.SENDER
     *
     * @return the value of cs_customer_group.SENDER
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    public String getSender() {
        return sender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_customer_group.SENDER
     *
     * @param sender the value for cs_customer_group.SENDER
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    public void setSender(String sender) {
        this.sender = sender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_customer_group.CONTENT
     *
     * @return the value of cs_customer_group.CONTENT
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_customer_group.CONTENT
     *
     * @param content the value for cs_customer_group.CONTENT
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_customer_group.END_TIME
     *
     * @return the value of cs_customer_group.END_TIME
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_customer_group.END_TIME
     *
     * @param endTime the value for cs_customer_group.END_TIME
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_customer_group.STATUS
     *
     * @return the value of cs_customer_group.STATUS
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_customer_group.STATUS
     *
     * @param status the value for cs_customer_group.STATUS
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_customer_group.CREATE_ID
     *
     * @return the value of cs_customer_group.CREATE_ID
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_customer_group.CREATE_ID
     *
     * @param createId the value for cs_customer_group.CREATE_ID
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_customer_group.CREATE_TIME
     *
     * @return the value of cs_customer_group.CREATE_TIME
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_customer_group.CREATE_TIME
     *
     * @param createTime the value for cs_customer_group.CREATE_TIME
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_customer_group.UPDATE_ID
     *
     * @return the value of cs_customer_group.UPDATE_ID
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    public Long getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_customer_group.UPDATE_ID
     *
     * @param updateId the value for cs_customer_group.UPDATE_ID
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    public void setUpdateId(Long updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_customer_group.UPDATE_TIME
     *
     * @return the value of cs_customer_group.UPDATE_TIME
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_customer_group.UPDATE_TIME
     *
     * @param updateTime the value for cs_customer_group.UPDATE_TIME
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_customer_group
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CustomerGroup other = (CustomerGroup) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCustomerGroupNo() == null ? other.getCustomerGroupNo() == null : this.getCustomerGroupNo().equals(other.getCustomerGroupNo()))
            && (this.getGroupFlag() == null ? other.getGroupFlag() == null : this.getGroupFlag().equals(other.getGroupFlag()))
            && (this.getNamespace() == null ? other.getNamespace() == null : this.getNamespace().equals(other.getNamespace()))
            && (this.getRoom() == null ? other.getRoom() == null : this.getRoom().equals(other.getRoom()))
            && (this.getPortrait() == null ? other.getPortrait() == null : this.getPortrait().equals(other.getPortrait()))
            && (this.getCustomerGroupName() == null ? other.getCustomerGroupName() == null : this.getCustomerGroupName().equals(other.getCustomerGroupName()))
            && (this.getSender() == null ? other.getSender() == null : this.getSender().equals(other.getSender()))
            && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()))
            && (this.getEndTime() == null ? other.getEndTime() == null : this.getEndTime().equals(other.getEndTime()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCreateId() == null ? other.getCreateId() == null : this.getCreateId().equals(other.getCreateId()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateId() == null ? other.getUpdateId() == null : this.getUpdateId().equals(other.getUpdateId()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_customer_group
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCustomerGroupNo() == null) ? 0 : getCustomerGroupNo().hashCode());
        result = prime * result + ((getGroupFlag() == null) ? 0 : getGroupFlag().hashCode());
        result = prime * result + ((getNamespace() == null) ? 0 : getNamespace().hashCode());
        result = prime * result + ((getRoom() == null) ? 0 : getRoom().hashCode());
        result = prime * result + ((getPortrait() == null) ? 0 : getPortrait().hashCode());
        result = prime * result + ((getCustomerGroupName() == null) ? 0 : getCustomerGroupName().hashCode());
        result = prime * result + ((getSender() == null) ? 0 : getSender().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        result = prime * result + ((getEndTime() == null) ? 0 : getEndTime().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCreateId() == null) ? 0 : getCreateId().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateId() == null) ? 0 : getUpdateId().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }
}