package com.lin.po;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class CustomerRels extends BasePo{
    public static final String OPT_FLAG_RECIPIENT = "1";  //1：接收者
    public static final String OPT_FLAG_APPLICANT = "0";  //0：申请者

    public static final String LEADER_FRIEND = "0"; // 普通好友
    public static final String LEADER_SUPER = "1";  //超级管理员
    public static final String LEADER_MANAGER = "2"; //管理员
    public static final String LEADER_UNIVERSAL = "3";  //普通员


    public static final String REL_FLAG_CUSTOMER = "0"; //客户关系
    public static final String REL_FLAG_GROUP = "1";    //群关系

    public static final String STATUS_INIT = "0"; //初始化
    public static final String STATUS_CONFIRM = "1"; //确认
    public static final String STATUS_REFUSE = "2"; //拒绝

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer_rels.ID
     *
     * @mbg.generated Tue Feb 15 21:47:34 CST 2022
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer_rels.CUSTOMER_ID
     *
     * @mbg.generated Tue Feb 15 21:47:34 CST 2022
     */
    private Long customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer_rels.CUSTOMER_GROUP_ID
     *
     * @mbg.generated Tue Feb 15 21:47:34 CST 2022
     */
    private Long customerGroupId;

    private Long customerRelId;
    /**
     * 0：申请者
     * 1：接收者
     */
    private String optFlag;

    /**
     * 0：好友
     * 1：超级管理员
     * 2：管理员
     * 3：普通会员
     */
    private String leader;

    /**
     * 0：客户，1：群
     */
    private String relFlag;

    /**
     * 0：申请中
     * 1：已经确认
     * 2：拒绝
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer_rels.CREATE_ID
     *
     * @mbg.generated Tue Feb 15 21:47:34 CST 2022
     */
    private String createId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer_rels.CREATE_TIME
     *
     * @mbg.generated Tue Feb 15 21:47:34 CST 2022
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer_rels.UPDATE_ID
     *
     * @mbg.generated Tue Feb 15 21:47:34 CST 2022
     */
    private String updateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer_rels.UPDATE_TIME
     *
     * @mbg.generated Tue Feb 15 21:47:34 CST 2022
     */
    private String updateTime;

}