package com.lin.po;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class CustomerGroup extends BasePo{
    public static final String STATUS_UNAVAILABLE = "0";  //不可用
    public static final String STATUS_AVAILABLE = "1";  //可用

    public static final String PRIVATE_FLAG = "0";  //可用
    public static final String PUBLIC_FLAG = "1";  //全部可见

    public static final String GROUP_FLAG_ONE = "0";  //好友 一对一
    public static final String GROUP_FLAG_MANY = "1";  //群 多对多
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer_group.ID
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer_group.CUSTOMER_GROUP_NO
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    private String customerGroupNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer_group.GROUP_FLAG
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    private String groupFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer_group.NAMESPACE
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    private String namespace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer_group.ROOM
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    private String room;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer_group.PORTRAIT
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    private String portrait;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer_group.CUSTOMER_GROUP_NAME
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    private String customerGroupName;

    private String purpose;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer_group.SENDER
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    private Long sender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer_group.CONTENT
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    private String content;
    private String privateFlag;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer_group.END_TIME
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    private String endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer_group.STATUS
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer_group.CREATE_ID
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    private Long createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer_group.CREATE_TIME
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer_group.UPDATE_ID
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    private Long updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer_group.UPDATE_TIME
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    private String updateTime;

    private CustomerRels customers;
}