package com.lin.po;

public class CustomerRels {
    public static final String OPT_FLAG_RECIPIENT = "1";  //1：接收者
    public static final String OPT_FLAG_APPLICANT = "0";  //0：申请者

    public static final String LEADER_FRIEND = "0"; // 普通好友
    public static final String LEADER_SUPER = "1";  //超级管理员
    public static final String LEADER_MANAGER = "2"; //管理员
    public static final String LEADER_UNIVERSAL = "3";  //普通员


    public static final String REL_FLAG_CUSTOMER = "0"; //客户关系
    public static final String REL_FLAG_GROUP = "1";    //群关系

    public static final String STATUS_INIT = "0"; //初始化
    public static final String STATUS_CONFIRM = "1"; //确认
    public static final String STATUS_REFUSE = "2"; //拒绝

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer_rels.ID
     *
     * @mbg.generated Tue Feb 15 21:47:34 CST 2022
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer_rels.CUSTOMER_ID
     *
     * @mbg.generated Tue Feb 15 21:47:34 CST 2022
     */
    private Long customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer_rels.CUSTOMER_GROUP_ID
     *
     * @mbg.generated Tue Feb 15 21:47:34 CST 2022
     */
    private Long customerGroupId;

    private Long customerRelId;
    /**
     * 0：申请者
     * 1：接收者
     */
    private String optFlag;

    /**
     * 0：好友
     * 1：超级管理员
     * 2：管理员
     * 3：普通会员
     */
    private String leader;

    /**
     * 0：客户，1：群
     */
    private String relFlag;

    /**
     * 0：申请中
     * 1：已经确认
     * 2：拒绝
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer_rels.CREATE_ID
     *
     * @mbg.generated Tue Feb 15 21:47:34 CST 2022
     */
    private String createId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer_rels.CREATE_TIME
     *
     * @mbg.generated Tue Feb 15 21:47:34 CST 2022
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer_rels.UPDATE_ID
     *
     * @mbg.generated Tue Feb 15 21:47:34 CST 2022
     */
    private String updateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer_rels.UPDATE_TIME
     *
     * @mbg.generated Tue Feb 15 21:47:34 CST 2022
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_customer_rels.ID
     *
     * @return the value of cs_customer_rels.ID
     * @mbg.generated Tue Feb 15 21:47:34 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_customer_rels.ID
     *
     * @param id the value for cs_customer_rels.ID
     * @mbg.generated Tue Feb 15 21:47:34 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_customer_rels.CUSTOMER_ID
     *
     * @return the value of cs_customer_rels.CUSTOMER_ID
     * @mbg.generated Tue Feb 15 21:47:34 CST 2022
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_customer_rels.CUSTOMER_ID
     *
     * @param customerId the value for cs_customer_rels.CUSTOMER_ID
     * @mbg.generated Tue Feb 15 21:47:34 CST 2022
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_customer_rels.CUSTOMER_GROUP_ID
     *
     * @return the value of cs_customer_rels.CUSTOMER_GROUP_ID
     * @mbg.generated Tue Feb 15 21:47:34 CST 2022
     */
    public Long getCustomerGroupId() {
        return customerGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_customer_rels.CUSTOMER_GROUP_ID
     *
     * @param customerGroupId the value for cs_customer_rels.CUSTOMER_GROUP_ID
     * @mbg.generated Tue Feb 15 21:47:34 CST 2022
     */
    public void setCustomerGroupId(Long customerGroupId) {
        this.customerGroupId = customerGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_customer_rels.OPT_FLAG
     *
     * @return the value of cs_customer_rels.OPT_FLAG
     * @mbg.generated Tue Feb 15 21:47:34 CST 2022
     */
    public String getOptFlag() {
        return optFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_customer_rels.OPT_FLAG
     *
     * @param optFlag the value for cs_customer_rels.OPT_FLAG
     * @mbg.generated Tue Feb 15 21:47:34 CST 2022
     */
    public void setOptFlag(String optFlag) {
        this.optFlag = optFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_customer_rels.LEADER
     *
     * @return the value of cs_customer_rels.LEADER
     * @mbg.generated Tue Feb 15 21:47:34 CST 2022
     */
    public String getLeader() {
        return leader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_customer_rels.LEADER
     *
     * @param leader the value for cs_customer_rels.LEADER
     * @mbg.generated Tue Feb 15 21:47:34 CST 2022
     */
    public void setLeader(String leader) {
        this.leader = leader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_customer_rels.REL_FLAG
     *
     * @return the value of cs_customer_rels.REL_FLAG
     * @mbg.generated Tue Feb 15 21:47:34 CST 2022
     */
    public String getRelFlag() {
        return relFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_customer_rels.REL_FLAG
     *
     * @param relFlag the value for cs_customer_rels.REL_FLAG
     * @mbg.generated Tue Feb 15 21:47:34 CST 2022
     */
    public void setRelFlag(String relFlag) {
        this.relFlag = relFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_customer_rels.STATUS
     *
     * @return the value of cs_customer_rels.STATUS
     * @mbg.generated Tue Feb 15 21:47:34 CST 2022
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_customer_rels.STATUS
     *
     * @param status the value for cs_customer_rels.STATUS
     * @mbg.generated Tue Feb 15 21:47:34 CST 2022
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_customer_rels.CREATE_ID
     *
     * @return the value of cs_customer_rels.CREATE_ID
     * @mbg.generated Tue Feb 15 21:47:34 CST 2022
     */
    public String getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_customer_rels.CREATE_ID
     *
     * @param createId the value for cs_customer_rels.CREATE_ID
     * @mbg.generated Tue Feb 15 21:47:34 CST 2022
     */
    public void setCreateId(String createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_customer_rels.CREATE_TIME
     *
     * @return the value of cs_customer_rels.CREATE_TIME
     * @mbg.generated Tue Feb 15 21:47:34 CST 2022
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_customer_rels.CREATE_TIME
     *
     * @param createTime the value for cs_customer_rels.CREATE_TIME
     * @mbg.generated Tue Feb 15 21:47:34 CST 2022
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_customer_rels.UPDATE_ID
     *
     * @return the value of cs_customer_rels.UPDATE_ID
     * @mbg.generated Tue Feb 15 21:47:34 CST 2022
     */
    public String getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_customer_rels.UPDATE_ID
     *
     * @param updateId the value for cs_customer_rels.UPDATE_ID
     * @mbg.generated Tue Feb 15 21:47:34 CST 2022
     */
    public void setUpdateId(String updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_customer_rels.UPDATE_TIME
     *
     * @return the value of cs_customer_rels.UPDATE_TIME
     * @mbg.generated Tue Feb 15 21:47:34 CST 2022
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_customer_rels.UPDATE_TIME
     *
     * @param updateTime the value for cs_customer_rels.UPDATE_TIME
     * @mbg.generated Tue Feb 15 21:47:34 CST 2022
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_customer_rels
     *
     * @mbg.generated Tue Feb 15 21:47:34 CST 2022
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CustomerRels other = (CustomerRels) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getCustomerId() == null ? other.getCustomerId() == null : this.getCustomerId().equals(other.getCustomerId()))
                && (this.getCustomerGroupId() == null ? other.getCustomerGroupId() == null : this.getCustomerGroupId().equals(other.getCustomerGroupId()))
                && (this.getOptFlag() == null ? other.getOptFlag() == null : this.getOptFlag().equals(other.getOptFlag()))
                && (this.getLeader() == null ? other.getLeader() == null : this.getLeader().equals(other.getLeader()))
                && (this.getRelFlag() == null ? other.getRelFlag() == null : this.getRelFlag().equals(other.getRelFlag()))
                && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
                && (this.getCreateId() == null ? other.getCreateId() == null : this.getCreateId().equals(other.getCreateId()))
                && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
                && (this.getUpdateId() == null ? other.getUpdateId() == null : this.getUpdateId().equals(other.getUpdateId()))
                && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_customer_rels
     *
     * @mbg.generated Tue Feb 15 21:47:34 CST 2022
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCustomerId() == null) ? 0 : getCustomerId().hashCode());
        result = prime * result + ((getCustomerGroupId() == null) ? 0 : getCustomerGroupId().hashCode());
        result = prime * result + ((getOptFlag() == null) ? 0 : getOptFlag().hashCode());
        result = prime * result + ((getLeader() == null) ? 0 : getLeader().hashCode());
        result = prime * result + ((getRelFlag() == null) ? 0 : getRelFlag().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCreateId() == null) ? 0 : getCreateId().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateId() == null) ? 0 : getUpdateId().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }
}