package com.lin.po;

public class Customer extends BasePo{

    public static final String GENDER_MALE = "male";  //男性
    public static final String GENDER_FEMALE = "female"; //女性
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer.ID
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer.CUSTOMER_NO
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    private String customerNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer.NAMESPACE
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    private String namespace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer.ROOM
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    private String room;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer.PORTRAIT
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    private String portrait;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer.PASSWORD
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer.OPENID
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    private String openid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer.LEVEL_NO
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    private String levelNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer.CUSTOMER_NAME
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    private String customerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer.GENDER
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer.NATION
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    private String nation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer.CARD_TYPE
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    private String cardType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer.CARD_NAME
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    private String cardName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer.CARD_ID
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    private String cardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer.MOBILE
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer.EMAIL
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer.STATUS
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer.CREATE_ID
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    private Long createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer.CREATE_TIME
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer.UPDATE_ID
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    private Long updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer.UPDATE_TIME
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_customer.ID
     *
     * @return the value of cs_customer.ID
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_customer.ID
     *
     * @param id the value for cs_customer.ID
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_customer.CUSTOMER_NO
     *
     * @return the value of cs_customer.CUSTOMER_NO
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    public String getCustomerNo() {
        return customerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_customer.CUSTOMER_NO
     *
     * @param customerNo the value for cs_customer.CUSTOMER_NO
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    public void setCustomerNo(String customerNo) {
        this.customerNo = customerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_customer.NAMESPACE
     *
     * @return the value of cs_customer.NAMESPACE
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    public String getNamespace() {
        return namespace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_customer.NAMESPACE
     *
     * @param namespace the value for cs_customer.NAMESPACE
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    public void setNamespace(String namespace) {
        this.namespace = namespace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_customer.ROOM
     *
     * @return the value of cs_customer.ROOM
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    public String getRoom() {
        return room;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_customer.ROOM
     *
     * @param room the value for cs_customer.ROOM
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    public void setRoom(String room) {
        this.room = room;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_customer.PORTRAIT
     *
     * @return the value of cs_customer.PORTRAIT
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    public String getPortrait() {
        return portrait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_customer.PORTRAIT
     *
     * @param portrait the value for cs_customer.PORTRAIT
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    public void setPortrait(String portrait) {
        this.portrait = portrait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_customer.PASSWORD
     *
     * @return the value of cs_customer.PASSWORD
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_customer.PASSWORD
     *
     * @param password the value for cs_customer.PASSWORD
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_customer.OPENID
     *
     * @return the value of cs_customer.OPENID
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_customer.OPENID
     *
     * @param openid the value for cs_customer.OPENID
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    public void setOpenid(String openid) {
        this.openid = openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_customer.LEVEL_NO
     *
     * @return the value of cs_customer.LEVEL_NO
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    public String getLevelNo() {
        return levelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_customer.LEVEL_NO
     *
     * @param levelNo the value for cs_customer.LEVEL_NO
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    public void setLevelNo(String levelNo) {
        this.levelNo = levelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_customer.CUSTOMER_NAME
     *
     * @return the value of cs_customer.CUSTOMER_NAME
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_customer.CUSTOMER_NAME
     *
     * @param customerName the value for cs_customer.CUSTOMER_NAME
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_customer.GENDER
     *
     * @return the value of cs_customer.GENDER
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_customer.GENDER
     *
     * @param gender the value for cs_customer.GENDER
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_customer.NATION
     *
     * @return the value of cs_customer.NATION
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_customer.NATION
     *
     * @param nation the value for cs_customer.NATION
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    public void setNation(String nation) {
        this.nation = nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_customer.CARD_TYPE
     *
     * @return the value of cs_customer.CARD_TYPE
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    public String getCardType() {
        return cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_customer.CARD_TYPE
     *
     * @param cardType the value for cs_customer.CARD_TYPE
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    public void setCardType(String cardType) {
        this.cardType = cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_customer.CARD_NAME
     *
     * @return the value of cs_customer.CARD_NAME
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    public String getCardName() {
        return cardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_customer.CARD_NAME
     *
     * @param cardName the value for cs_customer.CARD_NAME
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    public void setCardName(String cardName) {
        this.cardName = cardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_customer.CARD_ID
     *
     * @return the value of cs_customer.CARD_ID
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    public String getCardId() {
        return cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_customer.CARD_ID
     *
     * @param cardId the value for cs_customer.CARD_ID
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    public void setCardId(String cardId) {
        this.cardId = cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_customer.MOBILE
     *
     * @return the value of cs_customer.MOBILE
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_customer.MOBILE
     *
     * @param mobile the value for cs_customer.MOBILE
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_customer.EMAIL
     *
     * @return the value of cs_customer.EMAIL
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_customer.EMAIL
     *
     * @param email the value for cs_customer.EMAIL
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_customer.STATUS
     *
     * @return the value of cs_customer.STATUS
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_customer.STATUS
     *
     * @param status the value for cs_customer.STATUS
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_customer.CREATE_ID
     *
     * @return the value of cs_customer.CREATE_ID
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_customer.CREATE_ID
     *
     * @param createId the value for cs_customer.CREATE_ID
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_customer.CREATE_TIME
     *
     * @return the value of cs_customer.CREATE_TIME
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_customer.CREATE_TIME
     *
     * @param createTime the value for cs_customer.CREATE_TIME
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_customer.UPDATE_ID
     *
     * @return the value of cs_customer.UPDATE_ID
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    public Long getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_customer.UPDATE_ID
     *
     * @param updateId the value for cs_customer.UPDATE_ID
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    public void setUpdateId(Long updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_customer.UPDATE_TIME
     *
     * @return the value of cs_customer.UPDATE_TIME
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_customer.UPDATE_TIME
     *
     * @param updateTime the value for cs_customer.UPDATE_TIME
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_customer
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Customer other = (Customer) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCustomerNo() == null ? other.getCustomerNo() == null : this.getCustomerNo().equals(other.getCustomerNo()))
            && (this.getNamespace() == null ? other.getNamespace() == null : this.getNamespace().equals(other.getNamespace()))
            && (this.getRoom() == null ? other.getRoom() == null : this.getRoom().equals(other.getRoom()))
            && (this.getPortrait() == null ? other.getPortrait() == null : this.getPortrait().equals(other.getPortrait()))
            && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
            && (this.getOpenid() == null ? other.getOpenid() == null : this.getOpenid().equals(other.getOpenid()))
            && (this.getLevelNo() == null ? other.getLevelNo() == null : this.getLevelNo().equals(other.getLevelNo()))
            && (this.getCustomerName() == null ? other.getCustomerName() == null : this.getCustomerName().equals(other.getCustomerName()))
            && (this.getGender() == null ? other.getGender() == null : this.getGender().equals(other.getGender()))
            && (this.getNation() == null ? other.getNation() == null : this.getNation().equals(other.getNation()))
            && (this.getCardType() == null ? other.getCardType() == null : this.getCardType().equals(other.getCardType()))
            && (this.getCardName() == null ? other.getCardName() == null : this.getCardName().equals(other.getCardName()))
            && (this.getCardId() == null ? other.getCardId() == null : this.getCardId().equals(other.getCardId()))
            && (this.getMobile() == null ? other.getMobile() == null : this.getMobile().equals(other.getMobile()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCreateId() == null ? other.getCreateId() == null : this.getCreateId().equals(other.getCreateId()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateId() == null ? other.getUpdateId() == null : this.getUpdateId().equals(other.getUpdateId()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_customer
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCustomerNo() == null) ? 0 : getCustomerNo().hashCode());
        result = prime * result + ((getNamespace() == null) ? 0 : getNamespace().hashCode());
        result = prime * result + ((getRoom() == null) ? 0 : getRoom().hashCode());
        result = prime * result + ((getPortrait() == null) ? 0 : getPortrait().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getOpenid() == null) ? 0 : getOpenid().hashCode());
        result = prime * result + ((getLevelNo() == null) ? 0 : getLevelNo().hashCode());
        result = prime * result + ((getCustomerName() == null) ? 0 : getCustomerName().hashCode());
        result = prime * result + ((getGender() == null) ? 0 : getGender().hashCode());
        result = prime * result + ((getNation() == null) ? 0 : getNation().hashCode());
        result = prime * result + ((getCardType() == null) ? 0 : getCardType().hashCode());
        result = prime * result + ((getCardName() == null) ? 0 : getCardName().hashCode());
        result = prime * result + ((getCardId() == null) ? 0 : getCardId().hashCode());
        result = prime * result + ((getMobile() == null) ? 0 : getMobile().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCreateId() == null) ? 0 : getCreateId().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateId() == null) ? 0 : getUpdateId().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }
}