package com.lin.po;

public class Life extends BasePo{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_life.ID
     *
     * @mbg.generated Wed Apr 20 20:35:29 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_life.CUSTOMER_ID
     *
     * @mbg.generated Wed Apr 20 20:35:29 CST 2022
     */
    private Long customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_life.LABLES
     *
     * @mbg.generated Wed Apr 20 20:35:29 CST 2022
     */
    private Long lables;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_life.LIMIT_FLAG
     *
     * @mbg.generated Wed Apr 20 20:35:29 CST 2022
     */
    private String limitFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_life.CONTENTS
     *
     * @mbg.generated Wed Apr 20 20:35:29 CST 2022
     */
    private String contents;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_life.FILE_URL
     *
     * @mbg.generated Wed Apr 20 20:35:29 CST 2022
     */
    private String fileUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_life.PROVINCE
     *
     * @mbg.generated Wed Apr 20 20:35:29 CST 2022
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_life.CITY
     *
     * @mbg.generated Wed Apr 20 20:35:29 CST 2022
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_life.COUNTY
     *
     * @mbg.generated Wed Apr 20 20:35:29 CST 2022
     */
    private String county;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_life.THUMBSUP_TIMES
     *
     * @mbg.generated Wed Apr 20 20:35:29 CST 2022
     */
    private Integer thumbsupTimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_life.FORWARD_TIMES
     *
     * @mbg.generated Wed Apr 20 20:35:29 CST 2022
     */
    private Integer forwardTimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_life.REPLY_TIMES
     *
     * @mbg.generated Wed Apr 20 20:35:29 CST 2022
     */
    private Integer replyTimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_life.CREATE_ID
     *
     * @mbg.generated Wed Apr 20 20:35:29 CST 2022
     */
    private Long createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_life.CREATE_TIME
     *
     * @mbg.generated Wed Apr 20 20:35:29 CST 2022
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_life.UPDATE_ID
     *
     * @mbg.generated Wed Apr 20 20:35:29 CST 2022
     */
    private Long updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_life.UPDATE_TIME
     *
     * @mbg.generated Wed Apr 20 20:35:29 CST 2022
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_life.ID
     *
     * @return the value of cs_life.ID
     *
     * @mbg.generated Wed Apr 20 20:35:29 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_life.ID
     *
     * @param id the value for cs_life.ID
     *
     * @mbg.generated Wed Apr 20 20:35:29 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_life.CUSTOMER_ID
     *
     * @return the value of cs_life.CUSTOMER_ID
     *
     * @mbg.generated Wed Apr 20 20:35:29 CST 2022
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_life.CUSTOMER_ID
     *
     * @param customerId the value for cs_life.CUSTOMER_ID
     *
     * @mbg.generated Wed Apr 20 20:35:29 CST 2022
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_life.LABLES
     *
     * @return the value of cs_life.LABLES
     *
     * @mbg.generated Wed Apr 20 20:35:29 CST 2022
     */
    public Long getLables() {
        return lables;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_life.LABLES
     *
     * @param lables the value for cs_life.LABLES
     *
     * @mbg.generated Wed Apr 20 20:35:29 CST 2022
     */
    public void setLables(Long lables) {
        this.lables = lables;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_life.LIMIT_FLAG
     *
     * @return the value of cs_life.LIMIT_FLAG
     *
     * @mbg.generated Wed Apr 20 20:35:29 CST 2022
     */
    public String getLimitFlag() {
        return limitFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_life.LIMIT_FLAG
     *
     * @param limitFlag the value for cs_life.LIMIT_FLAG
     *
     * @mbg.generated Wed Apr 20 20:35:29 CST 2022
     */
    public void setLimitFlag(String limitFlag) {
        this.limitFlag = limitFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_life.CONTENTS
     *
     * @return the value of cs_life.CONTENTS
     *
     * @mbg.generated Wed Apr 20 20:35:29 CST 2022
     */
    public String getContents() {
        return contents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_life.CONTENTS
     *
     * @param contents the value for cs_life.CONTENTS
     *
     * @mbg.generated Wed Apr 20 20:35:29 CST 2022
     */
    public void setContents(String contents) {
        this.contents = contents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_life.FILE_URL
     *
     * @return the value of cs_life.FILE_URL
     *
     * @mbg.generated Wed Apr 20 20:35:29 CST 2022
     */
    public String getFileUrl() {
        return fileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_life.FILE_URL
     *
     * @param fileUrl the value for cs_life.FILE_URL
     *
     * @mbg.generated Wed Apr 20 20:35:29 CST 2022
     */
    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_life.PROVINCE
     *
     * @return the value of cs_life.PROVINCE
     *
     * @mbg.generated Wed Apr 20 20:35:29 CST 2022
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_life.PROVINCE
     *
     * @param province the value for cs_life.PROVINCE
     *
     * @mbg.generated Wed Apr 20 20:35:29 CST 2022
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_life.CITY
     *
     * @return the value of cs_life.CITY
     *
     * @mbg.generated Wed Apr 20 20:35:29 CST 2022
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_life.CITY
     *
     * @param city the value for cs_life.CITY
     *
     * @mbg.generated Wed Apr 20 20:35:29 CST 2022
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_life.COUNTY
     *
     * @return the value of cs_life.COUNTY
     *
     * @mbg.generated Wed Apr 20 20:35:29 CST 2022
     */
    public String getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_life.COUNTY
     *
     * @param county the value for cs_life.COUNTY
     *
     * @mbg.generated Wed Apr 20 20:35:29 CST 2022
     */
    public void setCounty(String county) {
        this.county = county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_life.THUMBSUP_TIMES
     *
     * @return the value of cs_life.THUMBSUP_TIMES
     *
     * @mbg.generated Wed Apr 20 20:35:29 CST 2022
     */
    public Integer getThumbsupTimes() {
        return thumbsupTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_life.THUMBSUP_TIMES
     *
     * @param thumbsupTimes the value for cs_life.THUMBSUP_TIMES
     *
     * @mbg.generated Wed Apr 20 20:35:29 CST 2022
     */
    public void setThumbsupTimes(Integer thumbsupTimes) {
        this.thumbsupTimes = thumbsupTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_life.FORWARD_TIMES
     *
     * @return the value of cs_life.FORWARD_TIMES
     *
     * @mbg.generated Wed Apr 20 20:35:29 CST 2022
     */
    public Integer getForwardTimes() {
        return forwardTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_life.FORWARD_TIMES
     *
     * @param forwardTimes the value for cs_life.FORWARD_TIMES
     *
     * @mbg.generated Wed Apr 20 20:35:29 CST 2022
     */
    public void setForwardTimes(Integer forwardTimes) {
        this.forwardTimes = forwardTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_life.REPLY_TIMES
     *
     * @return the value of cs_life.REPLY_TIMES
     *
     * @mbg.generated Wed Apr 20 20:35:29 CST 2022
     */
    public Integer getReplyTimes() {
        return replyTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_life.REPLY_TIMES
     *
     * @param replyTimes the value for cs_life.REPLY_TIMES
     *
     * @mbg.generated Wed Apr 20 20:35:29 CST 2022
     */
    public void setReplyTimes(Integer replyTimes) {
        this.replyTimes = replyTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_life.CREATE_ID
     *
     * @return the value of cs_life.CREATE_ID
     *
     * @mbg.generated Wed Apr 20 20:35:29 CST 2022
     */
    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_life.CREATE_ID
     *
     * @param createId the value for cs_life.CREATE_ID
     *
     * @mbg.generated Wed Apr 20 20:35:29 CST 2022
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_life.CREATE_TIME
     *
     * @return the value of cs_life.CREATE_TIME
     *
     * @mbg.generated Wed Apr 20 20:35:29 CST 2022
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_life.CREATE_TIME
     *
     * @param createTime the value for cs_life.CREATE_TIME
     *
     * @mbg.generated Wed Apr 20 20:35:29 CST 2022
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_life.UPDATE_ID
     *
     * @return the value of cs_life.UPDATE_ID
     *
     * @mbg.generated Wed Apr 20 20:35:29 CST 2022
     */
    public Long getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_life.UPDATE_ID
     *
     * @param updateId the value for cs_life.UPDATE_ID
     *
     * @mbg.generated Wed Apr 20 20:35:29 CST 2022
     */
    public void setUpdateId(Long updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_life.UPDATE_TIME
     *
     * @return the value of cs_life.UPDATE_TIME
     *
     * @mbg.generated Wed Apr 20 20:35:29 CST 2022
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_life.UPDATE_TIME
     *
     * @param updateTime the value for cs_life.UPDATE_TIME
     *
     * @mbg.generated Wed Apr 20 20:35:29 CST 2022
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_life
     *
     * @mbg.generated Wed Apr 20 20:35:29 CST 2022
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Life other = (Life) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCustomerId() == null ? other.getCustomerId() == null : this.getCustomerId().equals(other.getCustomerId()))
            && (this.getLables() == null ? other.getLables() == null : this.getLables().equals(other.getLables()))
            && (this.getLimitFlag() == null ? other.getLimitFlag() == null : this.getLimitFlag().equals(other.getLimitFlag()))
            && (this.getContents() == null ? other.getContents() == null : this.getContents().equals(other.getContents()))
            && (this.getFileUrl() == null ? other.getFileUrl() == null : this.getFileUrl().equals(other.getFileUrl()))
            && (this.getProvince() == null ? other.getProvince() == null : this.getProvince().equals(other.getProvince()))
            && (this.getCity() == null ? other.getCity() == null : this.getCity().equals(other.getCity()))
            && (this.getCounty() == null ? other.getCounty() == null : this.getCounty().equals(other.getCounty()))
            && (this.getThumbsupTimes() == null ? other.getThumbsupTimes() == null : this.getThumbsupTimes().equals(other.getThumbsupTimes()))
            && (this.getForwardTimes() == null ? other.getForwardTimes() == null : this.getForwardTimes().equals(other.getForwardTimes()))
            && (this.getReplyTimes() == null ? other.getReplyTimes() == null : this.getReplyTimes().equals(other.getReplyTimes()))
            && (this.getCreateId() == null ? other.getCreateId() == null : this.getCreateId().equals(other.getCreateId()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateId() == null ? other.getUpdateId() == null : this.getUpdateId().equals(other.getUpdateId()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_life
     *
     * @mbg.generated Wed Apr 20 20:35:29 CST 2022
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCustomerId() == null) ? 0 : getCustomerId().hashCode());
        result = prime * result + ((getLables() == null) ? 0 : getLables().hashCode());
        result = prime * result + ((getLimitFlag() == null) ? 0 : getLimitFlag().hashCode());
        result = prime * result + ((getContents() == null) ? 0 : getContents().hashCode());
        result = prime * result + ((getFileUrl() == null) ? 0 : getFileUrl().hashCode());
        result = prime * result + ((getProvince() == null) ? 0 : getProvince().hashCode());
        result = prime * result + ((getCity() == null) ? 0 : getCity().hashCode());
        result = prime * result + ((getCounty() == null) ? 0 : getCounty().hashCode());
        result = prime * result + ((getThumbsupTimes() == null) ? 0 : getThumbsupTimes().hashCode());
        result = prime * result + ((getForwardTimes() == null) ? 0 : getForwardTimes().hashCode());
        result = prime * result + ((getReplyTimes() == null) ? 0 : getReplyTimes().hashCode());
        result = prime * result + ((getCreateId() == null) ? 0 : getCreateId().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateId() == null) ? 0 : getUpdateId().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }
}