package com.lin.po;

public class Questions {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_questions.ID
     *
     * @mbg.generated Tue Apr 26 19:50:33 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_questions.标题
     *
     * @mbg.generated Tue Apr 26 19:50:33 CST 2022
     */
    private String 标题;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_questions.内容
     *
     * @mbg.generated Tue Apr 26 19:50:33 CST 2022
     */
    private String 内容;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_questions.文件URL
     *
     * @mbg.generated Tue Apr 26 19:50:33 CST 2022
     */
    private String 文件url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_questions.STATUS
     *
     * @mbg.generated Tue Apr 26 19:50:33 CST 2022
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_questions.CREATE_ID
     *
     * @mbg.generated Tue Apr 26 19:50:33 CST 2022
     */
    private Long createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_questions.CREATE_TIME
     *
     * @mbg.generated Tue Apr 26 19:50:33 CST 2022
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_questions.UPDATE_ID
     *
     * @mbg.generated Tue Apr 26 19:50:33 CST 2022
     */
    private Long updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_questions.UPDATE_TIME
     *
     * @mbg.generated Tue Apr 26 19:50:33 CST 2022
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_questions.ID
     *
     * @return the value of cs_questions.ID
     *
     * @mbg.generated Tue Apr 26 19:50:33 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_questions.ID
     *
     * @param id the value for cs_questions.ID
     *
     * @mbg.generated Tue Apr 26 19:50:33 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_questions.标题
     *
     * @return the value of cs_questions.标题
     *
     * @mbg.generated Tue Apr 26 19:50:33 CST 2022
     */
    public String get标题() {
        return 标题;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_questions.标题
     *
     * @param 标题 the value for cs_questions.标题
     *
     * @mbg.generated Tue Apr 26 19:50:33 CST 2022
     */
    public void set标题(String 标题) {
        this.标题 = 标题;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_questions.内容
     *
     * @return the value of cs_questions.内容
     *
     * @mbg.generated Tue Apr 26 19:50:33 CST 2022
     */
    public String get内容() {
        return 内容;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_questions.内容
     *
     * @param 内容 the value for cs_questions.内容
     *
     * @mbg.generated Tue Apr 26 19:50:33 CST 2022
     */
    public void set内容(String 内容) {
        this.内容 = 内容;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_questions.文件URL
     *
     * @return the value of cs_questions.文件URL
     *
     * @mbg.generated Tue Apr 26 19:50:33 CST 2022
     */
    public String get文件url() {
        return 文件url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_questions.文件URL
     *
     * @param 文件url the value for cs_questions.文件URL
     *
     * @mbg.generated Tue Apr 26 19:50:33 CST 2022
     */
    public void set文件url(String 文件url) {
        this.文件url = 文件url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_questions.STATUS
     *
     * @return the value of cs_questions.STATUS
     *
     * @mbg.generated Tue Apr 26 19:50:33 CST 2022
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_questions.STATUS
     *
     * @param status the value for cs_questions.STATUS
     *
     * @mbg.generated Tue Apr 26 19:50:33 CST 2022
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_questions.CREATE_ID
     *
     * @return the value of cs_questions.CREATE_ID
     *
     * @mbg.generated Tue Apr 26 19:50:33 CST 2022
     */
    public Long getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_questions.CREATE_ID
     *
     * @param createId the value for cs_questions.CREATE_ID
     *
     * @mbg.generated Tue Apr 26 19:50:33 CST 2022
     */
    public void setCreateId(Long createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_questions.CREATE_TIME
     *
     * @return the value of cs_questions.CREATE_TIME
     *
     * @mbg.generated Tue Apr 26 19:50:33 CST 2022
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_questions.CREATE_TIME
     *
     * @param createTime the value for cs_questions.CREATE_TIME
     *
     * @mbg.generated Tue Apr 26 19:50:33 CST 2022
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_questions.UPDATE_ID
     *
     * @return the value of cs_questions.UPDATE_ID
     *
     * @mbg.generated Tue Apr 26 19:50:33 CST 2022
     */
    public Long getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_questions.UPDATE_ID
     *
     * @param updateId the value for cs_questions.UPDATE_ID
     *
     * @mbg.generated Tue Apr 26 19:50:33 CST 2022
     */
    public void setUpdateId(Long updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_questions.UPDATE_TIME
     *
     * @return the value of cs_questions.UPDATE_TIME
     *
     * @mbg.generated Tue Apr 26 19:50:33 CST 2022
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_questions.UPDATE_TIME
     *
     * @param updateTime the value for cs_questions.UPDATE_TIME
     *
     * @mbg.generated Tue Apr 26 19:50:33 CST 2022
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_questions
     *
     * @mbg.generated Tue Apr 26 19:50:33 CST 2022
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Questions other = (Questions) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.get标题() == null ? other.get标题() == null : this.get标题().equals(other.get标题()))
            && (this.get内容() == null ? other.get内容() == null : this.get内容().equals(other.get内容()))
            && (this.get文件url() == null ? other.get文件url() == null : this.get文件url().equals(other.get文件url()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCreateId() == null ? other.getCreateId() == null : this.getCreateId().equals(other.getCreateId()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateId() == null ? other.getUpdateId() == null : this.getUpdateId().equals(other.getUpdateId()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_questions
     *
     * @mbg.generated Tue Apr 26 19:50:33 CST 2022
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((get标题() == null) ? 0 : get标题().hashCode());
        result = prime * result + ((get内容() == null) ? 0 : get内容().hashCode());
        result = prime * result + ((get文件url() == null) ? 0 : get文件url().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCreateId() == null) ? 0 : getCreateId().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateId() == null) ? 0 : getUpdateId().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }
}