package com.lin.controller.res;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class CustomerGroupResMsg {
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer_group.CUSTOMER_GROUP_NO
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    private String customerGroupNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer_group.GROUP_FLAG
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    private String groupFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer_group.NAMESPACE
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    private String namespace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer_group.ROOM
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    private String room;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer_group.PORTRAIT
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    private String portrait;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer_group.CUSTOMER_GROUP_NAME
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    private String customerGroupName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer_group.SENDER
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    private String sender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer_group.CONTENT
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer_group.END_TIME
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    private String endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer_group.STATUS
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer_group.CREATE_ID
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    private Long createId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer_group.CREATE_TIME
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer_group.UPDATE_ID
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    private Long updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer_group.UPDATE_TIME
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    private String updateTime;
}
