package com.lin.controller.res;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class CustomerResMsg {
    private String customerNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer.NAMESPACE
     *
     * @mbg.generated Wed Dec 22 10:16:36 CST 2021
     */
    private String namespace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer.ROOM
     *
     * @mbg.generated Wed Dec 22 10:16:36 CST 2021
     */
    private String room;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer.PORTRAIT
     *
     * @mbg.generated Wed Dec 22 10:16:36 CST 2021
     */
    private String portrait;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer.PASSWORD
     *
     * @mbg.generated Wed Dec 22 10:16:36 CST 2021
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer.OPENID
     *
     * @mbg.generated Wed Dec 22 10:16:36 CST 2021
     */
    private String openid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer.LEVEL_NO
     *
     * @mbg.generated Wed Dec 22 10:16:36 CST 2021
     */
    private String levelNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer.CUSTOMER_NAME
     *
     * @mbg.generated Wed Dec 22 10:16:36 CST 2021
     */
    private String customerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer.GENDER
     *
     * @mbg.generated Wed Dec 22 10:16:36 CST 2021
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer.NATION
     *
     * @mbg.generated Wed Dec 22 10:16:36 CST 2021
     */
    private String nation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer.CARD_TYPE
     *
     * @mbg.generated Wed Dec 22 10:16:36 CST 2021
     */
    private String cardType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer.CARD_NAME
     *
     * @mbg.generated Wed Dec 22 10:16:36 CST 2021
     */
    private String cardName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer.CARD_ID
     *
     * @mbg.generated Wed Dec 22 10:16:36 CST 2021
     */
    private String cardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer.MOBILE
     *
     * @mbg.generated Wed Dec 22 10:16:36 CST 2021
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer.EMAIL
     *
     * @mbg.generated Wed Dec 22 10:16:36 CST 2021
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cs_customer.STATUS
     *
     * @mbg.generated Wed Dec 22 10:16:36 CST 2021
     */
    private String status;
}
