package com.lin.dao;

import com.lin.po.Answers;

public interface AnswersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_answers
     *
     * @mbg.generated Tue Apr 26 19:48:50 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_answers
     *
     * @mbg.generated Tue Apr 26 19:48:50 CST 2022
     */
    int insert(Answers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_answers
     *
     * @mbg.generated Tue Apr 26 19:48:50 CST 2022
     */
    int insertSelective(Answers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_answers
     *
     * @mbg.generated Tue Apr 26 19:48:50 CST 2022
     */
    Answers selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_answers
     *
     * @mbg.generated Tue Apr 26 19:48:50 CST 2022
     */
    int updateByPrimaryKeySelective(Answers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_answers
     *
     * @mbg.generated Tue Apr 26 19:48:50 CST 2022
     */
    int updateByPrimaryKey(Answers record);
}