package com.lin.dao;

import com.lin.po.Customer;
import com.lin.po.CustomerRels;

import java.util.List;

public interface CustomerRelsMapper {

    /**
     * 查看好友是否存在正常关系，非查群关系
     * @param customerId
     * @return 返回关系好友
     */
    CustomerRels selectExistsByCustomerId(Long customerId,Long customerRelId);

    CustomerRels selecByCIdAndGId(CustomerRels customerRels);

    int insertBatch(List<CustomerRels> records);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_customer_rels
     *
     * @mbg.generated Tue Feb 15 21:47:34 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_customer_rels
     *
     * @mbg.generated Tue Feb 15 21:47:34 CST 2022
     */
    int insert(CustomerRels record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_customer_rels
     *
     * @mbg.generated Tue Feb 15 21:47:34 CST 2022
     */
    int insertSelective(CustomerRels record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_customer_rels
     *
     * @mbg.generated Tue Feb 15 21:47:34 CST 2022
     */
    CustomerRels selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_customer_rels
     *
     * @mbg.generated Tue Feb 15 21:47:34 CST 2022
     */
    int updateByPrimaryKeySelective(CustomerRels record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_customer_rels
     *
     * @mbg.generated Tue Feb 15 21:47:34 CST 2022
     */
    int updateByPrimaryKey(CustomerRels record);
}