package com.lin.dao;

import com.lin.po.Customer;

import java.util.List;

public interface CustomerMapper {

    Customer selectByEmail(String email);

    List<Customer> listrels(Customer c);

    Integer listrelscount(Long customerId);

    Customer byCustomerNo(String customerNo);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_customer
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_customer
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    int insert(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_customer
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    int insertSelective(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_customer
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    Customer selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_customer
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    int updateByPrimaryKeySelective(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_customer
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    int updateByPrimaryKey(Customer record);
}