package com.lin.dao;

import com.lin.po.Customer;
import com.lin.po.CustomerGroup;

import java.util.List;

public interface CustomerGroupMapper {

    List<CustomerGroup> listchats(Customer record);

    Integer listchatscount(Customer record);


    CustomerGroup selectGroupAndMember(Long id);

    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_customer_group
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    int insert(CustomerGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_customer_group
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    int insertSelective(CustomerGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_customer_group
     *
     * @mbg.generated Mon Feb 14 21:33:00 CST 2022
     */
    CustomerGroup selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_customer_group
     *
     * @mbg.generated Mon Feb 14 21:33:01 CST 2022
     */
    int updateByPrimaryKeySelective(CustomerGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_customer_group
     *
     * @mbg.generated Mon Feb 14 21:33:01 CST 2022
     */
    int updateByPrimaryKey(CustomerGroup record);
}