package com.lin.dao;

import com.lin.po.Customer;

import java.util.List;
import java.util.Map;

public interface CustomerMapper {

    Customer selectByEmail(String email);

    List<Customer> listrels(Map<String,Object> map);

    Integer listrelscount(Map<String,Object> map);

    Customer byCustomerNo(String customerNo);

    Customer selectRelationshipByCustomerId(String customerNo);

    Integer countByIds(List<Long> ids);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_customer
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_customer
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    int insert(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_customer
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    int insertSelective(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_customer
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    Customer selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_customer
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    int updateByPrimaryKeySelective(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_customer
     *
     * @mbg.generated Mon Feb 14 21:33:13 CST 2022
     */
    int updateByPrimaryKey(Customer record);
}