package com.lin.dao;

import com.lin.po.Chats;
import com.lin.po.Life;

import java.util.List;
import java.util.Map;

public interface LifeMapper {

    List<Chats> listlifes(Map<String,Object> map);

    Integer listlifescount(Map<String,Object> map);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_life
     *
     * @mbg.generated Wed Apr 20 20:35:29 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_life
     *
     * @mbg.generated Wed Apr 20 20:35:29 CST 2022
     */
    int insert(Life record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_life
     *
     * @mbg.generated Wed Apr 20 20:35:29 CST 2022
     */
    int insertSelective(Life record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_life
     *
     * @mbg.generated Wed Apr 20 20:35:29 CST 2022
     */
    Life selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_life
     *
     * @mbg.generated Wed Apr 20 20:35:29 CST 2022
     */
    int updateByPrimaryKeySelective(Life record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_life
     *
     * @mbg.generated Wed Apr 20 20:35:29 CST 2022
     */
    int updateByPrimaryKey(Life record);
}