package com.lin.dao;

import com.lin.po.Questions;

public interface QuestionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_questions
     *
     * @mbg.generated Tue Apr 26 19:50:33 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_questions
     *
     * @mbg.generated Tue Apr 26 19:50:33 CST 2022
     */
    int insert(Questions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_questions
     *
     * @mbg.generated Tue Apr 26 19:50:33 CST 2022
     */
    int insertSelective(Questions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_questions
     *
     * @mbg.generated Tue Apr 26 19:50:33 CST 2022
     */
    Questions selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_questions
     *
     * @mbg.generated Tue Apr 26 19:50:33 CST 2022
     */
    int updateByPrimaryKeySelective(Questions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_questions
     *
     * @mbg.generated Tue Apr 26 19:50:33 CST 2022
     */
    int updateByPrimaryKey(Questions record);
}